### ISSUE TITLE
DailyBatch returns [] when requesting only one symbol

### ISSUE THREAD

**Issue by mariusgrigoriu** [spacecodewor/fmpcloud-go#4]
DailyBatch returns [] when requesting only one symbol. This is due to the fact that FMP uses a different json format when there is only one symbol. It would be nice if the library could handle this case so we don't need to put a conditional in our code to make a different call if there is only one symbol to look up.

**Comment by spacecodewor** [comment]
Hi, in ver 2.5.0 you can check this logic

**Comment by spacecodewor** [comment]
> DailyBatch returns [] when requesting only one symbol. This is due to the fact that FMP uses a different json format when there is only one symbol. It would be nice if the library could handle this case so we don't need to put a conditional in our code to make a different call if there is only one symbol to look up.

Hi, in ver 2.5.0 you can check this logic

**Comment by mariusgrigoriu** [comment]
It looks good. Thanks!
