### ISSUE TITLE
Export Resty client or allow custom http.Client

### ISSUE THREAD

**Issue by mariusgrigoriu** [spacecodewor/fmpcloud-go#5]
It would be nice if the resty.Client created in https://github.com/spacecodewor/fmpcloud-go/blob/00b9fb5b9925ef3375b6be27d4dfb5c4d19f1535/client.go#L70 were exported (ideally in APIClient) or if Config would take a custom http.Client for resty. This would facilitate testing code that depends on the fmpcloud library using tools like httpmock: https://github.com/go-resty/resty#mocking-http-requests-using-httpmock-library

What do you think?

**Comment by spacecodewor** [comment]
> It would be nice if the resty.Client created in
> 
> https://github.com/spacecodewor/fmpcloud-go/blob/00b9fb5b9925ef3375b6be27d4dfb5c4d19f1535/client.go#L70
> 
> were exported (ideally in APIClient) or if Config would take a custom http.Client for resty. This would facilitate testing code that depends on the fmpcloud library using tools like httpmock: https://github.com/go-resty/resty#mocking-http-requests-using-httpmock-library
> What do you think?

Hi, I think this is a good idea. I will do it soon.

**Comment by spacecodewor** [comment]
Hi, check in ver 2.6.0

**Comment by mariusgrigoriu** [comment]
Confirmed it works. Thank you.
