### ISSUE TITLE
EbtPerEbit should be float64

### ISSUE THREAD

**Issue by blup** [spacecodewor/fmpcloud-go#6]
Thank you for this library! I received the following error while calling client.CompanyValuation.FinancialRatios: `json: cannot unmarshal number 0.9819078947368421 into Go struct field FinancialRatios.ebtPerEbit of type int64`. It seems like FinancialRatios.EbtPerEbit should be a float64 instead of an int64.

Unrelated to this error, i was wondering if there's a reason for KeyMetrics.DividendYield and KeyMetridcs.InvestedCapital to be `*float64` instead of `float64`.

**Comment by spacecodewor** [comment]
> Thank you for this library! I received the following error while calling client.CompanyValuation.FinancialRatios: `json: cannot unmarshal number 0.9819078947368421 into Go struct field FinancialRatios.ebtPerEbit of type int64`. It seems like FinancialRatios.EbtPerEbit should be a float64 instead of an int64.
> 
> Unrelated to this error, i was wondering if there's a reason for KeyMetrics.DividendYield and KeyMetridcs.InvestedCapital to be `*float64` instead of `float64`.

Hi evaporated in version 2.7.0

About * float64 to float64
Sometimes null is added to the ovette, I wanted to do it and not guess where is really 0 or not 0.

But I never used this, I removed it in this structure

**Comment by blup** [comment]
Perfect, thanks again for the quick response!
